/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;
import controller.LoginController;

/**
 *
 * @author sanug
 */
public class AddAppointmentView extends javax.swing.JFrame {

    /**
     * Creates new form AddAppointmentView
     */
    private NewSchedulleSinglyLinkedList listOne;
    
    public AddAppointmentView() {
        
        initComponents();
        addInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBgMain2 = new javax.swing.JPanel();
        panelBgTop2 = new javax.swing.JPanel();
        lblClose2 = new javax.swing.JLabel();
        lblFrameHeading = new javax.swing.JLabel();
        lblProfilePng1 = new javax.swing.JLabel();
        lblProfilePng = new javax.swing.JLabel();
        panelBgProfile = new javax.swing.JPanel();
        lblUseranme = new javax.swing.JLabel();
        lblUseranme1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUseranme7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tlbAllAppointments = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblHome13 = new javax.swing.JLabel();
        txtFirst = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        lblHome14 = new javax.swing.JLabel();
        txtLast = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        lblHome15 = new javax.swing.JLabel();
        txtNic = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        lblHome16 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        lblHome17 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        lblHome18 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblUseranme3 = new javax.swing.JLabel();
        lblErrorFirstName = new javax.swing.JLabel();
        lblErrorLastName = new javax.swing.JLabel();
        lblErrorNic = new javax.swing.JLabel();
        lblErrorAddress = new javax.swing.JLabel();
        lblErrorMobile = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        txtNicNoDelete = new javax.swing.JTextField();
        lblHome21 = new javax.swing.JLabel();
        lblErrorSearch = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tlbDelete = new javax.swing.JTable();
        jPanel20 = new javax.swing.JPanel();
        btnDelte = new javax.swing.JButton();
        lblUseranme10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tlbCurrentPatient = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tlbNextPatient = new javax.swing.JTable();
        btnNext = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        lblUseranme8 = new javax.swing.JLabel();
        lblUseranme9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        lblHome22 = new javax.swing.JLabel();
        lblProfilePng3 = new javax.swing.JLabel();
        txtTotalAppointments = new javax.swing.JLabel();
        lblHome20 = new javax.swing.JLabel();
        lblProfilePng4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        lblHome24 = new javax.swing.JLabel();
        lblProfilePng5 = new javax.swing.JLabel();
        txtReamainAppointments = new javax.swing.JLabel();
        lblHome26 = new javax.swing.JLabel();
        lblProfilePng6 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        lblHome27 = new javax.swing.JLabel();
        lblProfilePng7 = new javax.swing.JLabel();
        txtFinishedAppointments = new javax.swing.JLabel();
        lblHome28 = new javax.swing.JLabel();
        lblProfilePng8 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBackupRestore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBgMain2.setBackground(new java.awt.Color(255, 255, 255));

        panelBgTop2.setBackground(new java.awt.Color(218, 242, 250));

        lblClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/close.png"))); // NOI18N
        lblClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose2MouseClicked(evt);
            }
        });

        lblFrameHeading.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblFrameHeading.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading.setText("Appointments");

        lblProfilePng1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cardiogram (1).png"))); // NOI18N

        lblProfilePng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/profile-user (1).png"))); // NOI18N

        panelBgProfile.setBackground(new java.awt.Color(218, 242, 250));

        lblUseranme.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUseranme.setText("Mrs. Amaya Weerathunga");

        lblUseranme1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblUseranme1.setText("Nurse");

        javax.swing.GroupLayout panelBgProfileLayout = new javax.swing.GroupLayout(panelBgProfile);
        panelBgProfile.setLayout(panelBgProfileLayout);
        panelBgProfileLayout.setHorizontalGroup(
            panelBgProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBgProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUseranme, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUseranme1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        panelBgProfileLayout.setVerticalGroup(
            panelBgProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgProfileLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUseranme)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUseranme1))
        );

        javax.swing.GroupLayout panelBgTop2Layout = new javax.swing.GroupLayout(panelBgTop2);
        panelBgTop2.setLayout(panelBgTop2Layout);
        panelBgTop2Layout.setHorizontalGroup(
            panelBgTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBgTop2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblProfilePng1)
                .addGap(18, 18, 18)
                .addComponent(lblFrameHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 897, Short.MAX_VALUE)
                .addComponent(lblProfilePng)
                .addGap(18, 18, 18)
                .addComponent(panelBgProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(lblClose2)
                .addGap(18, 18, 18))
        );
        panelBgTop2Layout.setVerticalGroup(
            panelBgTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgTop2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBgTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblClose2)
                    .addGroup(panelBgTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblFrameHeading, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProfilePng1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblProfilePng))
                .addGap(10, 10, 10))
            .addGroup(panelBgTop2Layout.createSequentialGroup()
                .addComponent(panelBgProfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblUseranme7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUseranme7.setForeground(new java.awt.Color(170, 170, 170));
        lblUseranme7.setText("Current Appointments");

        tlbAllAppointments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tlbAllAppointments.setRowHeight(35);
        jScrollPane5.setViewportView(tlbAllAppointments);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUseranme7, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUseranme7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(601, 648));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        lblHome13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome13.setForeground(new java.awt.Color(170, 170, 170));
        lblHome13.setText("First Name");

        txtFirst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFirst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFirstMouseClicked(evt);
            }
        });
        txtFirst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(lblHome13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHome13)
                    .addComponent(txtFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 47, 402, 47));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        lblHome14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome14.setForeground(new java.awt.Color(170, 170, 170));
        lblHome14.setText("Last Name");

        txtLast.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtLast.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLastMouseClicked(evt);
            }
        });
        txtLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastActionPerformed(evt);
            }
        });
        txtLast.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(lblHome14, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHome14)
                    .addComponent(txtLast, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 112, -1, 47));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        lblHome15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome15.setForeground(new java.awt.Color(170, 170, 170));
        lblHome15.setText("Nic");

        txtNic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtNic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNicMouseClicked(evt);
            }
        });
        txtNic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNicKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(lblHome15, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHome15)
                    .addComponent(txtNic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 177, 402, 47));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        lblHome16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome16.setForeground(new java.awt.Color(170, 170, 170));
        lblHome16.setText("Address");

        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAddressMouseClicked(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAddressKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(lblHome16, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHome16)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 246, 402, 47));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        lblHome17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome17.setForeground(new java.awt.Color(170, 170, 170));
        lblHome17.setText("Mobile");

        txtMobile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtMobile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMobileMouseClicked(evt);
            }
        });
        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMobileKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(lblHome17, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHome17)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 311, 402, 47));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        lblHome18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome18.setForeground(new java.awt.Color(170, 170, 170));
        lblHome18.setText("Email");

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(lblHome18, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHome18)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 376, 402, 47));

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(11, 60, 77));
        btnAdd.setText("ADD");
        btnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 60, 77)));
        btnAdd.setContentAreaFilled(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });
        jPanel2.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 468, 142, 46));

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(11, 60, 77));
        btnClear.setText("CLEAR");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 60, 77)));
        btnClear.setContentAreaFilled(false);
        btnClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnClearKeyPressed(evt);
            }
        });
        jPanel2.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 468, 142, 46));

        lblUseranme3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUseranme3.setForeground(new java.awt.Color(170, 170, 170));
        lblUseranme3.setText("New Appointments");
        jPanel2.add(lblUseranme3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 9, 289, -1));

        lblErrorFirstName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblErrorFirstName.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorFirstName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/error (1).png"))); // NOI18N
        lblErrorFirstName.setText("Error!");
        jPanel2.add(lblErrorFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 62, 190, -1));

        lblErrorLastName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblErrorLastName.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorLastName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/error (1).png"))); // NOI18N
        lblErrorLastName.setText("Error!");
        jPanel2.add(lblErrorLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 126, 190, -1));

        lblErrorNic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblErrorNic.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorNic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/error (1).png"))); // NOI18N
        lblErrorNic.setText("Error!");
        jPanel2.add(lblErrorNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 192, 180, -1));

        lblErrorAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblErrorAddress.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorAddress.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/error (1).png"))); // NOI18N
        lblErrorAddress.setText("Error!");
        jPanel2.add(lblErrorAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 258, 190, -1));

        lblErrorMobile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblErrorMobile.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorMobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/error (1).png"))); // NOI18N
        lblErrorMobile.setText("Error!");
        jPanel2.add(lblErrorMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 325, 190, -1));

        lblErrorEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblErrorEmail.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/error (1).png"))); // NOI18N
        lblErrorEmail.setText("Error!");
        jPanel2.add(lblErrorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 389, 190, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        lblHome21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome21.setForeground(new java.awt.Color(170, 170, 170));
        lblHome21.setText("NIC No:");

        lblErrorSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblErrorSearch.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/error (1).png"))); // NOI18N
        lblErrorSearch.setText("Error!");

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(11, 60, 77));
        btnSearch.setText("SEARCH");
        btnSearch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 60, 77)));
        btnSearch.setContentAreaFilled(false);
        btnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome21, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblErrorSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNicNoDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNicNoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHome21)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorSearch)
                .addGap(12, 12, 12))
        );

        tlbDelete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tlbDelete.setRowHeight(35);
        jScrollPane2.setViewportView(tlbDelete);

        jPanel20.setBackground(new java.awt.Color(170, 170, 170));
        jPanel20.setForeground(new java.awt.Color(11, 60, 77));
        jPanel20.setPreferredSize(new java.awt.Dimension(0, 2));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        btnDelte.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnDelte.setForeground(new java.awt.Color(11, 60, 77));
        btnDelte.setText("DELETE");
        btnDelte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 60, 77)));
        btnDelte.setContentAreaFilled(false);
        btnDelte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelteActionPerformed(evt);
            }
        });

        lblUseranme10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUseranme10.setForeground(new java.awt.Color(170, 170, 170));
        lblUseranme10.setText("Cancel Appointment");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblUseranme10, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUseranme10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnDelte, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tlbCurrentPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tlbCurrentPatient.setRowHeight(35);
        jScrollPane3.setViewportView(tlbCurrentPatient);

        tlbNextPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tlbNextPatient.setRowHeight(35);
        jScrollPane4.setViewportView(tlbNextPatient);

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnNext.setForeground(new java.awt.Color(11, 60, 77));
        btnNext.setText("NEXT ");
        btnNext.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 60, 77)));
        btnNext.setContentAreaFilled(false);
        btnNext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jPanel18.setBackground(new java.awt.Color(170, 170, 170));
        jPanel18.setForeground(new java.awt.Color(11, 60, 77));
        jPanel18.setPreferredSize(new java.awt.Dimension(547, 1));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        lblUseranme8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUseranme8.setForeground(new java.awt.Color(170, 170, 170));
        lblUseranme8.setText("Current Patient");

        lblUseranme9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblUseranme9.setForeground(new java.awt.Color(170, 170, 170));
        lblUseranme9.setText("Next Patient");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUseranme9, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUseranme8, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                        .addComponent(jScrollPane3)
                        .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUseranme8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(lblUseranme9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));

        jPanel21.setBackground(new java.awt.Color(11, 60, 77));
        jPanel21.setForeground(new java.awt.Color(255, 102, 153));

        lblHome22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome22.setForeground(new java.awt.Color(255, 255, 255));
        lblHome22.setText("More details");

        lblProfilePng3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProfilePng3)
                .addGap(18, 18, 18))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng3)
                    .addComponent(lblHome22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtTotalAppointments.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtTotalAppointments.setForeground(new java.awt.Color(11, 60, 77));
        txtTotalAppointments.setText("12");

        lblHome20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHome20.setForeground(new java.awt.Color(11, 60, 77));
        lblHome20.setText("Total Appointments");

        lblProfilePng4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblProfilePng4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lblHome20)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtTotalAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(txtTotalAppointments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHome20)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(lblProfilePng4)
                        .addGap(44, 44, 44)))
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 153, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(247, 186));

        jPanel22.setBackground(new java.awt.Color(11, 60, 77));
        jPanel22.setForeground(new java.awt.Color(255, 102, 153));

        lblHome24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome24.setForeground(new java.awt.Color(255, 255, 255));
        lblHome24.setText("More details");

        lblProfilePng5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProfilePng5)
                .addGap(18, 18, 18))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng5)
                    .addComponent(lblHome24))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        txtReamainAppointments.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtReamainAppointments.setForeground(new java.awt.Color(11, 60, 77));
        txtReamainAppointments.setText("12");

        lblHome26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHome26.setForeground(new java.awt.Color(11, 60, 77));
        lblHome26.setText(" Remain");

        lblProfilePng6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblProfilePng6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtReamainAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHome26))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(txtReamainAppointments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHome26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(lblProfilePng6)
                        .addGap(29, 29, 29)))
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel23.setBackground(new java.awt.Color(255, 102, 102));
        jPanel23.setPreferredSize(new java.awt.Dimension(327, 186));

        jPanel24.setBackground(new java.awt.Color(11, 60, 77));
        jPanel24.setForeground(new java.awt.Color(255, 102, 153));

        lblHome27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome27.setForeground(new java.awt.Color(255, 255, 255));
        lblHome27.setText("More details");

        lblProfilePng7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProfilePng7)
                .addGap(18, 18, 18))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng7)
                    .addComponent(lblHome27))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        txtFinishedAppointments.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtFinishedAppointments.setForeground(new java.awt.Color(11, 60, 77));
        txtFinishedAppointments.setText("12");

        lblHome28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHome28.setForeground(new java.awt.Color(11, 60, 77));
        lblHome28.setText("Finished ");

        lblProfilePng8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (2).png"))); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblProfilePng8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFinishedAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblHome28, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addComponent(txtFinishedAppointments)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblHome28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addComponent(lblProfilePng8)
                        .addGap(29, 29, 29)))
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel19.setBackground(new java.awt.Color(170, 170, 170));
        jPanel19.setForeground(new java.awt.Color(11, 60, 77));
        jPanel19.setPreferredSize(new java.awt.Dimension(3, 183));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/Picture2.png"))); // NOI18N

        btnBackupRestore.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBackupRestore.setForeground(new java.awt.Color(255, 51, 102));
        btnBackupRestore.setText("Backup Restore");
        btnBackupRestore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 102), 2));
        btnBackupRestore.setContentAreaFilled(false);
        btnBackupRestore.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackupRestore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupRestoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBgMain2Layout = new javax.swing.GroupLayout(panelBgMain2);
        panelBgMain2.setLayout(panelBgMain2Layout);
        panelBgMain2Layout.setHorizontalGroup(
            panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBgTop2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBgMain2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBgMain2Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBgMain2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(panelBgMain2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                            .addComponent(btnBackupRestore, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23))))
        );
        panelBgMain2Layout.setVerticalGroup(
            panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgMain2Layout.createSequentialGroup()
                .addComponent(panelBgTop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBgMain2Layout.createSequentialGroup()
                        .addGroup(panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBgMain2Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBgMain2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelBgMain2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelBgMain2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBackupRestore, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBgMain2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBgMain2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose2MouseClicked
        
        int c = JOptionPane.showConfirmDialog(null, "Do you want to Logout From the System?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (c == 0) {
            
            new LoginController().setLogin(0, "", "");
            new LoginView().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_lblClose2MouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        clearError();
        if (txtFirst.getText().equals("")) {
            lblErrorFirstName.setText("Cannot be null!");
            lblErrorFirstName.setVisible(true);
        }
        else if(txtFirst.getText().matches(".*\\d.*")){
            lblErrorFirstName.setText("Cannot have numbers!");
            lblErrorFirstName.setVisible(true);
        }
        else if(txtLast.getText().equals("")){
            lblErrorLastName.setText("Cannot be null!");
            lblErrorLastName.setVisible(true);
        }
        else if(txtLast.getText().matches(".*\\d.*")){
            lblErrorLastName.setText("Cannot have numbers!");
            lblErrorLastName.setVisible(true);
        }
        else if(txtNic.getText().equals("")){
            lblErrorNic.setText("Cannot be null!");
            lblErrorNic.setVisible(true);
        }
        else if(txtNic.getText().length()<10 || txtNic.getText().length()>12 || txtNic.getText().length()==11){
            lblErrorNic.setText("Incorrect nic nubmer!");
            lblErrorNic.setVisible(true);
        }
        else if(txtAddress.getText().equals("")){
            lblErrorAddress.setText("Cannot be null!");
            lblErrorAddress.setVisible(true);
        }
        else if(txtMobile.getText().equals("")){
            lblErrorMobile.setText("Cannot be null!");
            lblErrorMobile.setVisible(true);
        }
        else if(txtMobile.getText().length()!=10){
            lblErrorMobile.setText("Incorrect mobile number!");
            lblErrorMobile.setVisible(true);
        }
        else if(!(txtMobile.getText().matches("[0-9]+"))){
            lblErrorMobile.setText("Incorrect mobile number!");
            lblErrorMobile.setVisible(true);
        }
        else if(txtEmail.getText().equals("")){
            lblErrorEmail.setText("Cannot be null!");
            lblErrorEmail.setVisible(true);
        }
         else if(!(txtEmail.getText().matches("^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{3}$"))){
            lblErrorEmail.setText("Incorrect Email Address!");
            lblErrorEmail.setVisible(true);                
        }
        else {

            try {
                Statement st = DataBaseModel.createConnection().createStatement();
                int c = st.executeUpdate("INSERT into appointment_tlb (sno,fname,lname,nic,address,mobile,email) VALUES ("+new LoginController().getSchedulleId()+",'" + txtFirst.getText() + "','" + txtLast.getText() + "','" + txtNic.getText() + "','" + txtAddress.getText() + "'," + Integer.parseInt(txtMobile.getText()) + ",'" + txtEmail.getText() + "')");
                ResultSet rst = st.executeQuery("SELECT MAX(aid) FROM appointment_tlb");
                rst.next();
                if (c > 0) {
                    
                    listOne.insertEnding(rst.getInt(1), txtFirst.getText(), txtLast.getText(), txtNic.getText(), txtAddress.getText(), Integer.parseInt(txtMobile.getText()), txtEmail.getText());
                    refresh();
                    JOptionPane.showMessageDialog(null,"Data is recorded successfully","Information",JOptionPane.INFORMATION_MESSAGE);
                    clearTextBoxes();
                    clearError();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Data is not recorded successfully!","Error!",JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(),"Error!",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void refresh() {
        clearError();
        clearTextBoxes();
        txtTotalAppointments.setText(String.valueOf(listOne.getTotalAppointments()));
        txtFinishedAppointments.setText(String.valueOf(listOne.getFinishedAppointments()));
        txtReamainAppointments.setText(String.valueOf(listOne.getRemainAppointments()));
        viewAllAppointments();
        viewCurrentPatient();
        viewNextPatient();
    }

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        clearError();
        clearTextBoxes();
    }//GEN-LAST:event_btnClearActionPerformed

    private void addInformation() {
        clearError();
        clearTextBoxes();
        lblUseranme.setText(new LoginController().getFirstName());
        listOne = new NewSchedulleSinglyLinkedList();
        refresh();
    }

    private void clearError() {
        lblErrorFirstName.setVisible(false);
        lblErrorLastName.setVisible(false);
        lblErrorNic.setVisible(false);
        lblErrorAddress.setVisible(false);
        lblErrorMobile.setVisible(false);
        lblErrorEmail.setVisible(false);
        lblErrorSearch.setVisible(false);
    }

    private void clearTextBoxes() {
        txtFirst.setText("");
        txtLast.setText("");
        txtAddress.setText("");
        txtEmail.setText("");
        txtMobile.setText("");
        txtNic.setText("");
        txtNicNoDelete.setText("");
    }

    private void viewAllAppointments(){
        DefaultTableModel model = listOne.viewAllAppointments();
        tlbAllAppointments.setModel(model);
    }

    private void viewCurrentPatient() {
        DefaultTableModel model = listOne.viewCurrentPatient();
        tlbCurrentPatient.setModel(model);
    }

    private void viewNextPatient() {
        DefaultTableModel model = listOne.viewNextPatient();
        tlbNextPatient.setModel(model);
    }

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        try {
            Statement st = DataBaseModel.createConnection().createStatement();
            if (listOne.getHeadNode() != null) {
                int c = st.executeUpdate("DELETE FROM appointment_tlb WHERE nic='" + listOne.getHeadNode().getNic() + "'");
                if (c > 0) {
                    listOne.removeBegining();
                    refresh();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnDelteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelteActionPerformed
        // TODO add your handling code here:
        clearError();
        if (txtNicNoDelete.getText().equals("")) {
            lblErrorSearch.setText("Cannot be null!");
            lblErrorSearch.setVisible(true);
        } else if (txtNicNoDelete.getText().length() < 10 || txtNicNoDelete.getText().length() > 12 || txtNicNoDelete.getText().length() == 11) {
            lblErrorSearch.setText("Incorrect nic nubmer!");
            lblErrorSearch.setVisible(true);
        } else {
            try {
                Statement st = DataBaseModel.createConnection().createStatement();
                int c = st.executeUpdate("DELETE FROM appointment_tlb WHERE nic='" + txtNicNoDelete.getText() + "'");
                if (c > 0) {
                    listOne.removeThis(txtNicNoDelete.getText());
                    refresh();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_btnDelteActionPerformed

    private void txtLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        clearError();
        if (txtNicNoDelete.getText().equals("")) {
            lblErrorSearch.setText("Cannot be null!");
            lblErrorSearch.setVisible(true);
        } else if (txtNicNoDelete.getText().length() < 10 || txtNicNoDelete.getText().length() > 12 || txtNicNoDelete.getText().length() == 11) {
            lblErrorSearch.setText("Incorrect nic nubmer!");
            lblErrorSearch.setVisible(true);
        } else {
            tlbDelete.setModel(listOne.viewNicPatientToDelete(txtNicNoDelete.getText()));
            
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnClearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnClearKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearKeyPressed

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddKeyPressed

    private void txtFirstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstKeyPressed

    private void txtLastKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastKeyPressed

    private void txtNicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNicKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicKeyPressed

    private void txtAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressKeyPressed

    private void txtMobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileKeyPressed

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtFirstMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFirstMouseClicked
        // TODO add your handling code here:
        clearError();
    }//GEN-LAST:event_txtFirstMouseClicked

    private void txtLastMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLastMouseClicked
        // TODO add your handling code here:
        clearError();
    }//GEN-LAST:event_txtLastMouseClicked

    private void txtNicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNicMouseClicked
        // TODO add your handling code here:
        clearError();
    }//GEN-LAST:event_txtNicMouseClicked

    private void txtAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAddressMouseClicked
        // TODO add your handling code here:
        clearError();
    }//GEN-LAST:event_txtAddressMouseClicked

    private void txtMobileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMobileMouseClicked
        // TODO add your handling code here:
        clearError();
    }//GEN-LAST:event_txtMobileMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
        clearError();
    }//GEN-LAST:event_txtEmailMouseClicked

    private void btnBackupRestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupRestoreActionPerformed
        // TODO add your handling code here:
        try {
            int c = JOptionPane.showConfirmDialog(null, "Do you want to restore the entire system?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);

            if (c == 0) {
                Statement st = DataBaseModel.createConnection().createStatement();
                ResultSet rst = st.executeQuery("SELECT * FROM appointment_tlb WHERE sno="+new LoginController().getSchedulleId()+" ORDER BY aid");
                while (rst.next()) {
                    listOne.insertEnding(rst.getInt(1), rst.getString(3), rst.getString(4), rst.getString(5), rst.getString(6), rst.getInt(7), rst.getString(8));
                }
                refresh();

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBackupRestoreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAppointmentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAppointmentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackupRestore;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelte;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblClose2;
    private javax.swing.JLabel lblErrorAddress;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorFirstName;
    private javax.swing.JLabel lblErrorLastName;
    private javax.swing.JLabel lblErrorMobile;
    private javax.swing.JLabel lblErrorNic;
    private javax.swing.JLabel lblErrorSearch;
    private javax.swing.JLabel lblFrameHeading;
    private javax.swing.JLabel lblHome13;
    private javax.swing.JLabel lblHome14;
    private javax.swing.JLabel lblHome15;
    private javax.swing.JLabel lblHome16;
    private javax.swing.JLabel lblHome17;
    private javax.swing.JLabel lblHome18;
    private javax.swing.JLabel lblHome20;
    private javax.swing.JLabel lblHome21;
    private javax.swing.JLabel lblHome22;
    private javax.swing.JLabel lblHome24;
    private javax.swing.JLabel lblHome26;
    private javax.swing.JLabel lblHome27;
    private javax.swing.JLabel lblHome28;
    private javax.swing.JLabel lblProfilePng;
    private javax.swing.JLabel lblProfilePng1;
    private javax.swing.JLabel lblProfilePng3;
    private javax.swing.JLabel lblProfilePng4;
    private javax.swing.JLabel lblProfilePng5;
    private javax.swing.JLabel lblProfilePng6;
    private javax.swing.JLabel lblProfilePng7;
    private javax.swing.JLabel lblProfilePng8;
    private javax.swing.JLabel lblUseranme;
    private javax.swing.JLabel lblUseranme1;
    private javax.swing.JLabel lblUseranme10;
    private javax.swing.JLabel lblUseranme3;
    private javax.swing.JLabel lblUseranme7;
    private javax.swing.JLabel lblUseranme8;
    private javax.swing.JLabel lblUseranme9;
    private javax.swing.JPanel panelBgMain2;
    private javax.swing.JPanel panelBgProfile;
    private javax.swing.JPanel panelBgTop2;
    private javax.swing.JTable tlbAllAppointments;
    private javax.swing.JTable tlbCurrentPatient;
    private javax.swing.JTable tlbDelete;
    private javax.swing.JTable tlbNextPatient;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtFinishedAppointments;
    private javax.swing.JTextField txtFirst;
    private javax.swing.JTextField txtLast;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtNic;
    private javax.swing.JTextField txtNicNoDelete;
    private javax.swing.JLabel txtReamainAppointments;
    private javax.swing.JLabel txtTotalAppointments;
    // End of variables declaration//GEN-END:variables
}
