/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;
import model.DataBaseModel;

/**
 *
 * @author sanug
 */
public class DashBoardView extends javax.swing.JFrame {

    /**
     * Creates new form DashBoardView
     */
    private int room1Count = 0;
    private int room2Count = 0;
    private int room3Count = 0;
    private int room4Count = 0;
    private int room5Count = 0;
    private int room1NCount = 0;
    private int room2NCount = 0;
    private int room3NCount = 0;
    private int room4NCount = 0;
    private int room5NCount = 0;

    public DashBoardView() {
        initComponents();
        addInformation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBgMain = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        panelBgLeftSide1 = new javax.swing.JPanel();
        lblHomeIcon = new javax.swing.JLabel();
        lblReportIcon = new javax.swing.JLabel();
        lblProfilePng = new javax.swing.JLabel();
        lblProfilePng1 = new javax.swing.JLabel();
        lblHomeIcon1 = new javax.swing.JLabel();
        lblFrameHeading = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panelRoom2 = new javax.swing.JPanel();
        lblFrameHeading22 = new javax.swing.JLabel();
        panelRoom1 = new javax.swing.JPanel();
        lblFrameHeading21 = new javax.swing.JLabel();
        panelRoom4 = new javax.swing.JPanel();
        lblFrameHeading24 = new javax.swing.JLabel();
        panelRoom3 = new javax.swing.JPanel();
        lblFrameHeading23 = new javax.swing.JLabel();
        panelRoom5 = new javax.swing.JPanel();
        lblFrameHeading31 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        barRoomN3 = new javax.swing.JPanel();
        lblHome22 = new javax.swing.JLabel();
        lblProfilePng3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblFrameHeading5 = new javax.swing.JLabel();
        lblCountRoom3N = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        barRoomN4 = new javax.swing.JPanel();
        lblHome25 = new javax.swing.JLabel();
        lblProfilePng6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblFrameHeading7 = new javax.swing.JLabel();
        lblCountRoom4N = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        barRoomN2 = new javax.swing.JPanel();
        lblHome26 = new javax.swing.JLabel();
        lblProfilePng7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblFrameHeading3 = new javax.swing.JLabel();
        lblCountRoom2N = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        barRoomN1 = new javax.swing.JPanel();
        lblHome27 = new javax.swing.JLabel();
        lblProfilePng8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblFrameHeading2 = new javax.swing.JLabel();
        lblCountRoom1N = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        barRoomN5 = new javax.swing.JPanel();
        lblHome28 = new javax.swing.JLabel();
        lblProfilePng9 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblFrameHeading9 = new javax.swing.JLabel();
        lblCountRoom5N = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        barRoom3 = new javax.swing.JPanel();
        lblHome29 = new javax.swing.JLabel();
        lblProfilePng10 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lblFrameHeading11 = new javax.swing.JLabel();
        lblCountRoom3 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        barRoom4 = new javax.swing.JPanel();
        lblHome30 = new javax.swing.JLabel();
        lblProfilePng11 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        lblFrameHeading13 = new javax.swing.JLabel();
        lblCountRoom4 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        barRoom2 = new javax.swing.JPanel();
        lblHome31 = new javax.swing.JLabel();
        lblProfilePng12 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        lblFrameHeading15 = new javax.swing.JLabel();
        lblCountRoom2 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        barRoom1 = new javax.swing.JPanel();
        lblHome32 = new javax.swing.JLabel();
        lblProfilePng13 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        lblFrameHeading17 = new javax.swing.JLabel();
        lblCountRoom1 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        barRoom5 = new javax.swing.JPanel();
        lblHome33 = new javax.swing.JLabel();
        lblProfilePng14 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        lblFrameHeading19 = new javax.swing.JLabel();
        lblCountRoom5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tlbAllPatients = new javax.swing.JTable();
        lblFrameHeading30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBgMain.setBackground(new java.awt.Color(255, 255, 255));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/close.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });

        panelBgLeftSide1.setBackground(new java.awt.Color(218, 242, 250));

        lblHomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/home-icon-silhouette (1).png"))); // NOI18N
        lblHomeIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblHomeIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeIconMouseClicked(evt);
            }
        });

        lblReportIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReportIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (4).png"))); // NOI18N
        lblReportIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblReportIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportIconMouseClicked(evt);
            }
        });

        lblProfilePng.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/profile-user (1).png"))); // NOI18N

        lblProfilePng1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/cardiogram (1).png"))); // NOI18N

        lblHomeIcon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHomeIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (5).png"))); // NOI18N
        lblHomeIcon1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelBgLeftSide1Layout = new javax.swing.GroupLayout(panelBgLeftSide1);
        panelBgLeftSide1.setLayout(panelBgLeftSide1Layout);
        panelBgLeftSide1Layout.setHorizontalGroup(
            panelBgLeftSide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgLeftSide1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBgLeftSide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblReportIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProfilePng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProfilePng1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHomeIcon1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHomeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        panelBgLeftSide1Layout.setVerticalGroup(
            panelBgLeftSide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgLeftSide1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblProfilePng1)
                .addGap(144, 144, 144)
                .addComponent(lblHomeIcon)
                .addGap(18, 18, 18)
                .addComponent(lblReportIcon)
                .addGap(18, 18, 18)
                .addComponent(lblHomeIcon1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                .addComponent(lblProfilePng)
                .addGap(25, 25, 25))
        );

        lblFrameHeading.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading.setText("Home");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panelRoom2.setBackground(new java.awt.Color(255, 0, 51));

        lblFrameHeading22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFrameHeading22.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading22.setText("Room 02");

        javax.swing.GroupLayout panelRoom2Layout = new javax.swing.GroupLayout(panelRoom2);
        panelRoom2.setLayout(panelRoom2Layout);
        panelRoom2Layout.setHorizontalGroup(
            panelRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRoom2Layout.setVerticalGroup(
            panelRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelRoom1.setBackground(new java.awt.Color(255, 0, 51));

        lblFrameHeading21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFrameHeading21.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading21.setText("Room 01");

        javax.swing.GroupLayout panelRoom1Layout = new javax.swing.GroupLayout(panelRoom1);
        panelRoom1.setLayout(panelRoom1Layout);
        panelRoom1Layout.setHorizontalGroup(
            panelRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRoom1Layout.setVerticalGroup(
            panelRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading21, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelRoom4.setBackground(new java.awt.Color(255, 0, 51));

        lblFrameHeading24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFrameHeading24.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading24.setText("Room 04");

        javax.swing.GroupLayout panelRoom4Layout = new javax.swing.GroupLayout(panelRoom4);
        panelRoom4.setLayout(panelRoom4Layout);
        panelRoom4Layout.setHorizontalGroup(
            panelRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRoom4Layout.setVerticalGroup(
            panelRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading24, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelRoom3.setBackground(new java.awt.Color(255, 0, 51));

        lblFrameHeading23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFrameHeading23.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading23.setText("Room 03");

        javax.swing.GroupLayout panelRoom3Layout = new javax.swing.GroupLayout(panelRoom3);
        panelRoom3.setLayout(panelRoom3Layout);
        panelRoom3Layout.setHorizontalGroup(
            panelRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRoom3Layout.setVerticalGroup(
            panelRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelRoom5.setBackground(new java.awt.Color(255, 0, 51));

        lblFrameHeading31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFrameHeading31.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading31.setText("Room 05");

        javax.swing.GroupLayout panelRoom5Layout = new javax.swing.GroupLayout(panelRoom5);
        panelRoom5.setLayout(panelRoom5Layout);
        panelRoom5Layout.setHorizontalGroup(
            panelRoom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading31)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        panelRoom5Layout.setVerticalGroup(
            panelRoom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRoom5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(11, 60, 77));
        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 60, 77)));
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        btnRefresh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnRefreshKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelRoom5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRoom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRoom4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRoom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRoom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(panelRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRoom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRoom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRoom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRoom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(204, 0, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoomN3.setBackground(new java.awt.Color(11, 60, 77));
        barRoomN3.setForeground(new java.awt.Color(255, 102, 153));
        barRoomN3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoomN3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoomN3MouseClicked(evt);
            }
        });

        lblHome22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome22.setForeground(new java.awt.Color(255, 255, 255));
        lblHome22.setText("Room No 03");

        lblProfilePng3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoomN3Layout = new javax.swing.GroupLayout(barRoomN3);
        barRoomN3.setLayout(barRoomN3Layout);
        barRoomN3Layout.setHorizontalGroup(
            barRoomN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProfilePng3)
                .addGap(18, 18, 18))
        );
        barRoomN3Layout.setVerticalGroup(
            barRoomN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoomN3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng3)
                    .addComponent(lblHome22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(barRoomN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 193, -1));

        jPanel12.setBackground(new java.awt.Color(204, 0, 204));

        lblFrameHeading5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading5.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom3N.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom3N.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom3N.setText("00");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom3N)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom3N)
                    .addComponent(lblFrameHeading5))
                .addContainerGap())
        );

        jPanel5.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoomN4.setBackground(new java.awt.Color(11, 60, 77));
        barRoomN4.setForeground(new java.awt.Color(255, 102, 153));
        barRoomN4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoomN4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoomN4MouseClicked(evt);
            }
        });

        lblHome25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome25.setForeground(new java.awt.Color(255, 255, 255));
        lblHome25.setText("Room No 04");

        lblProfilePng6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoomN4Layout = new javax.swing.GroupLayout(barRoomN4);
        barRoomN4.setLayout(barRoomN4Layout);
        barRoomN4Layout.setHorizontalGroup(
            barRoomN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lblProfilePng6)
                .addGap(18, 18, 18))
        );
        barRoomN4Layout.setVerticalGroup(
            barRoomN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoomN4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng6)
                    .addComponent(lblHome25))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.add(barRoomN4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel13.setBackground(new java.awt.Color(0, 153, 153));

        lblFrameHeading7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading7.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom4N.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom4N.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom4N.setText("00");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom4N)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom4N)
                    .addComponent(lblFrameHeading7))
                .addContainerGap())
        );

        jPanel8.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jPanel9.setBackground(new java.awt.Color(102, 204, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoomN2.setBackground(new java.awt.Color(11, 60, 77));
        barRoomN2.setForeground(new java.awt.Color(255, 102, 153));
        barRoomN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoomN2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoomN2MouseClicked(evt);
            }
        });

        lblHome26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome26.setForeground(new java.awt.Color(255, 255, 255));
        lblHome26.setText("Room No 02");

        lblProfilePng7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoomN2Layout = new javax.swing.GroupLayout(barRoomN2);
        barRoomN2.setLayout(barRoomN2Layout);
        barRoomN2Layout.setHorizontalGroup(
            barRoomN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lblProfilePng7)
                .addGap(18, 18, 18))
        );
        barRoomN2Layout.setVerticalGroup(
            barRoomN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoomN2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng7)
                    .addComponent(lblHome26))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.add(barRoomN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel4.setBackground(new java.awt.Color(102, 204, 255));

        lblFrameHeading3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading3.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom2N.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom2N.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom2N.setText("00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom2N)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom2N)
                    .addComponent(lblFrameHeading3))
                .addContainerGap())
        );

        jPanel9.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoomN1.setBackground(new java.awt.Color(11, 60, 77));
        barRoomN1.setForeground(new java.awt.Color(255, 102, 153));
        barRoomN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoomN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoomN1MouseClicked(evt);
            }
        });

        lblHome27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome27.setForeground(new java.awt.Color(255, 255, 255));
        lblHome27.setText("Room No 01");

        lblProfilePng8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoomN1Layout = new javax.swing.GroupLayout(barRoomN1);
        barRoomN1.setLayout(barRoomN1Layout);
        barRoomN1Layout.setHorizontalGroup(
            barRoomN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lblProfilePng8)
                .addGap(18, 18, 18))
        );
        barRoomN1Layout.setVerticalGroup(
            barRoomN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoomN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng8)
                    .addComponent(lblHome27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.add(barRoomN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        lblFrameHeading2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading2.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom1N.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom1N.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom1N.setText("00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom1N)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom1N)
                    .addComponent(lblFrameHeading2))
                .addContainerGap())
        );

        jPanel10.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jPanel11.setBackground(new java.awt.Color(255, 153, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoomN5.setBackground(new java.awt.Color(11, 60, 77));
        barRoomN5.setForeground(new java.awt.Color(255, 102, 153));
        barRoomN5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoomN5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoomN5MouseClicked(evt);
            }
        });

        lblHome28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome28.setForeground(new java.awt.Color(255, 255, 255));
        lblHome28.setText("Room No 05");

        lblProfilePng9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoomN5Layout = new javax.swing.GroupLayout(barRoomN5);
        barRoomN5.setLayout(barRoomN5Layout);
        barRoomN5Layout.setHorizontalGroup(
            barRoomN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lblProfilePng9)
                .addGap(18, 18, 18))
        );
        barRoomN5Layout.setVerticalGroup(
            barRoomN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoomN5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoomN5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng9)
                    .addComponent(lblHome28))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.add(barRoomN5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel14.setBackground(new java.awt.Color(255, 153, 51));

        lblFrameHeading9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading9.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom5N.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom5N.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom5N.setText("00");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom5N)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom5N)
                    .addComponent(lblFrameHeading9))
                .addContainerGap())
        );

        jPanel11.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(204, 204, 204));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoom3.setBackground(new java.awt.Color(11, 60, 77));
        barRoom3.setForeground(new java.awt.Color(255, 102, 153));
        barRoom3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoom3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoom3MouseClicked(evt);
            }
        });

        lblHome29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome29.setForeground(new java.awt.Color(255, 255, 255));
        lblHome29.setText("Room No 03");

        lblProfilePng10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoom3Layout = new javax.swing.GroupLayout(barRoom3);
        barRoom3.setLayout(barRoom3Layout);
        barRoom3Layout.setHorizontalGroup(
            barRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProfilePng10)
                .addGap(18, 18, 18))
        );
        barRoom3Layout.setVerticalGroup(
            barRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng10)
                    .addComponent(lblHome29))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel16.add(barRoom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 193, -1));

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));

        lblFrameHeading11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading11.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom3.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom3.setText("00");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom3)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom3)
                    .addComponent(lblFrameHeading11))
                .addContainerGap())
        );

        jPanel16.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 48, -1, -1));

        jPanel18.setBackground(new java.awt.Color(153, 255, 153));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoom4.setBackground(new java.awt.Color(11, 60, 77));
        barRoom4.setForeground(new java.awt.Color(255, 102, 153));
        barRoom4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoom4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoom4MouseClicked(evt);
            }
        });

        lblHome30.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome30.setForeground(new java.awt.Color(255, 255, 255));
        lblHome30.setText("Room No 04");

        lblProfilePng11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoom4Layout = new javax.swing.GroupLayout(barRoom4);
        barRoom4.setLayout(barRoom4Layout);
        barRoom4Layout.setHorizontalGroup(
            barRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lblProfilePng11)
                .addGap(18, 18, 18))
        );
        barRoom4Layout.setVerticalGroup(
            barRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng11)
                    .addComponent(lblHome30))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.add(barRoom4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel19.setBackground(new java.awt.Color(153, 255, 153));

        lblFrameHeading13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading13.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom4.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom4.setText("00");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom4)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom4)
                    .addComponent(lblFrameHeading13))
                .addContainerGap())
        );

        jPanel18.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jPanel15.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 48, 193, -1));

        jPanel20.setBackground(new java.awt.Color(51, 102, 255));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoom2.setBackground(new java.awt.Color(11, 60, 77));
        barRoom2.setForeground(new java.awt.Color(255, 102, 153));
        barRoom2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoom2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoom2MouseClicked(evt);
            }
        });

        lblHome31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome31.setForeground(new java.awt.Color(255, 255, 255));
        lblHome31.setText("Room No 02");

        lblProfilePng12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoom2Layout = new javax.swing.GroupLayout(barRoom2);
        barRoom2.setLayout(barRoom2Layout);
        barRoom2Layout.setHorizontalGroup(
            barRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(lblProfilePng12)
                .addGap(18, 18, 18))
        );
        barRoom2Layout.setVerticalGroup(
            barRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng12)
                    .addComponent(lblHome31))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.add(barRoom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel31.setBackground(new java.awt.Color(51, 102, 255));

        lblFrameHeading15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading15.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom2.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom2.setText("00");

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel31Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom2)
                    .addComponent(lblFrameHeading15))
                .addContainerGap())
        );

        jPanel20.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jPanel15.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 48, 193, -1));

        jPanel32.setBackground(new java.awt.Color(204, 204, 0));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoom1.setBackground(new java.awt.Color(11, 60, 77));
        barRoom1.setForeground(new java.awt.Color(255, 102, 153));
        barRoom1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoom1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoom1MouseClicked(evt);
            }
        });

        lblHome32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome32.setForeground(new java.awt.Color(255, 255, 255));
        lblHome32.setText("Room No 01");

        lblProfilePng13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoom1Layout = new javax.swing.GroupLayout(barRoom1);
        barRoom1.setLayout(barRoom1Layout);
        barRoom1Layout.setHorizontalGroup(
            barRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lblProfilePng13)
                .addGap(18, 18, 18))
        );
        barRoom1Layout.setVerticalGroup(
            barRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng13)
                    .addComponent(lblHome32))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel32.add(barRoom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel34.setBackground(new java.awt.Color(204, 204, 0));

        lblFrameHeading17.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading17.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom1.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom1.setText("00");

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom1)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel34Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom1)
                    .addComponent(lblFrameHeading17))
                .addContainerGap())
        );

        jPanel32.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jPanel15.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, -1, -1));

        jPanel35.setBackground(new java.awt.Color(153, 153, 255));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barRoom5.setBackground(new java.awt.Color(11, 60, 77));
        barRoom5.setForeground(new java.awt.Color(255, 102, 153));
        barRoom5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barRoom5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barRoom5MouseClicked(evt);
            }
        });

        lblHome33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHome33.setForeground(new java.awt.Color(255, 255, 255));
        lblHome33.setText("Room No 05");

        lblProfilePng14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/arrow-right.png"))); // NOI18N

        javax.swing.GroupLayout barRoom5Layout = new javax.swing.GroupLayout(barRoom5);
        barRoom5.setLayout(barRoom5Layout);
        barRoom5Layout.setHorizontalGroup(
            barRoom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lblProfilePng14)
                .addGap(18, 18, 18))
        );
        barRoom5Layout.setVerticalGroup(
            barRoom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barRoom5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(barRoom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfilePng14)
                    .addComponent(lblHome33))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel35.add(barRoom5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel37.setBackground(new java.awt.Color(153, 153, 255));

        lblFrameHeading19.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblFrameHeading19.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/calendar (3).png"))); // NOI18N

        lblCountRoom5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblCountRoom5.setForeground(new java.awt.Color(11, 60, 77));
        lblCountRoom5.setText("00");

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFrameHeading19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCountRoom5)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel37Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblCountRoom5)
                    .addComponent(lblFrameHeading19))
                .addContainerGap())
        );

        jPanel35.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 11, -1, -1));

        jPanel15.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(817, 48, -1, -1));

        tlbAllPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tlbAllPatients.setRowHeight(35);
        jScrollPane3.setViewportView(tlbAllPatients);

        lblFrameHeading30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFrameHeading30.setForeground(new java.awt.Color(11, 60, 77));
        lblFrameHeading30.setText("Room 01");

        javax.swing.GroupLayout panelBgMainLayout = new javax.swing.GroupLayout(panelBgMain);
        panelBgMain.setLayout(panelBgMainLayout);
        panelBgMainLayout.setHorizontalGroup(
            panelBgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBgMainLayout.createSequentialGroup()
                .addComponent(panelBgLeftSide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(panelBgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBgMainLayout.createSequentialGroup()
                        .addGroup(panelBgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBgMainLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(panelBgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))
                            .addGroup(panelBgMainLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelBgMainLayout.createSequentialGroup()
                        .addComponent(lblFrameHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblClose)
                        .addGap(25, 25, 25))))
            .addGroup(panelBgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBgMainLayout.createSequentialGroup()
                    .addGap(610, 610, 610)
                    .addComponent(lblFrameHeading30)
                    .addContainerGap(611, Short.MAX_VALUE)))
        );
        panelBgMainLayout.setVerticalGroup(
            panelBgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBgLeftSide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelBgMainLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelBgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFrameHeading)
                    .addComponent(lblClose))
                .addGroup(panelBgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBgMainLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBgMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(panelBgMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBgMainLayout.createSequentialGroup()
                    .addGap(390, 390, 390)
                    .addComponent(lblFrameHeading30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(391, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBgMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBgMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        int c = JOptionPane.showConfirmDialog(null, "Do you want to Logout From the System?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);
        
        if (c == 0) {
            
            new LoginController().setLogin(0, "", "");
            new LoginView().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        addInformation();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRefreshKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnRefreshKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshKeyPressed

    private void fillTable(int sno){
        try {
            DefaultTableModel model = new DefaultTableModel();
            Statement st = DataBaseModel.createConnection().createStatement();
            ResultSet rst = st.executeQuery("SELECT * FROM appointment_tlb WHERE sno = "+sno+"");
            model.addColumn("Id");
            model.addColumn("First");
            model.addColumn("Last");
            model.addColumn("NIC");
            model.addColumn("Address");
            model.addColumn("Mobile");
            model.addColumn("Email");
            while (rst.next()) {
                String[] arr = new String[7];
                arr[0] = String.valueOf(rst.getInt(1));
                arr[1] = String.valueOf(rst.getString(3));
                arr[2] = String.valueOf(rst.getString(4));
                arr[3] = String.valueOf(rst.getString(5));
                arr[4] = String.valueOf(rst.getString(6));
                arr[5] = String.valueOf(rst.getInt(7));
                arr[6] = String.valueOf(rst.getString(8));
                model.addRow(arr);
            }
            tlbAllPatients.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void barRoom1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoom1MouseClicked
        // TODO add your handling code here:
        fillTable(1);
    }//GEN-LAST:event_barRoom1MouseClicked

    private void barRoom2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoom2MouseClicked
        // TODO add your handling code here:
        fillTable(2);
    }//GEN-LAST:event_barRoom2MouseClicked

    private void barRoom3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoom3MouseClicked
        // TODO add your handling code here:
        fillTable(3);
    }//GEN-LAST:event_barRoom3MouseClicked

    private void barRoom4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoom4MouseClicked
        // TODO add your handling code here:
        fillTable(4);
    }//GEN-LAST:event_barRoom4MouseClicked

    private void barRoom5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoom5MouseClicked
        // TODO add your handling code here:
        fillTable(5);
    }//GEN-LAST:event_barRoom5MouseClicked

    private void barRoomN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoomN1MouseClicked
        // TODO add your handling code here:
        fillTable(6);
    }//GEN-LAST:event_barRoomN1MouseClicked

    private void barRoomN2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoomN2MouseClicked
        // TODO add your handling code here:
        fillTable(7);
    }//GEN-LAST:event_barRoomN2MouseClicked

    private void barRoomN3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoomN3MouseClicked
        // TODO add your handling code here:
        fillTable(8);
    }//GEN-LAST:event_barRoomN3MouseClicked

    private void barRoomN4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoomN4MouseClicked
        // TODO add your handling code here:
        fillTable(9);
    }//GEN-LAST:event_barRoomN4MouseClicked

    private void barRoomN5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barRoomN5MouseClicked
        // TODO add your handling code here:
        fillTable(10);
    }//GEN-LAST:event_barRoomN5MouseClicked

    private void lblHomeIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeIconMouseClicked
        // TODO add your handling code here:
        new DashBoardView().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblHomeIconMouseClicked

    private void lblReportIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportIconMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblReportIconMouseClicked

    private void refresh() {

        room1Count = 0;
        room2Count = 0;
        room3Count = 0;
        room4Count = 0;
        room5Count = 0;
        room1NCount = 0;
        room2NCount = 0;
        room3NCount = 0;
        room4NCount = 0;
        room5NCount = 0;

        lblCountRoom1.setText(String.valueOf(00));
        lblCountRoom2.setText(String.valueOf(00));
        lblCountRoom3.setText(String.valueOf(00));
        lblCountRoom4.setText(String.valueOf(00));
        lblCountRoom5.setText(String.valueOf(00));
        lblCountRoom1N.setText(String.valueOf(00));
        lblCountRoom2N.setText(String.valueOf(00));
        lblCountRoom3N.setText(String.valueOf(00));
        lblCountRoom4N.setText(String.valueOf(00));
        lblCountRoom5N.setText(String.valueOf(00));

        panelRoom1.setBackground(Color.RED);
        panelRoom2.setBackground(Color.RED);
        panelRoom3.setBackground(Color.RED);
        panelRoom4.setBackground(Color.RED);
        panelRoom5.setBackground(Color.RED);
    }

    private void addInformation() {
        try {
            Statement st = DataBaseModel.createConnection().createStatement();
            ResultSet rst = st.executeQuery("SELECT sno,COUNT(aid) FROM appointment_tlb GROUP BY sno ORDER BY COUNT(aid) ");
            refresh();
            while (rst.next()) {
                switch (rst.getInt(1)) {
                    case 1:
                        room1Count = rst.getInt(2);
                        lblCountRoom1.setText(String.valueOf(room1Count));
                        break;
                    case 2:
                        room2Count = rst.getInt(2);
                        lblCountRoom2.setText(String.valueOf(room2Count));
                        break;
                    case 3:
                        room3Count = rst.getInt(2);
                        lblCountRoom3.setText(String.valueOf(room3Count));
                        break;
                    case 4:
                        room4Count = rst.getInt(2);
                        lblCountRoom4.setText(String.valueOf(room4Count));
                        break;
                    case 5:
                        room5Count = rst.getInt(2);
                        lblCountRoom5.setText(String.valueOf(room5Count));
                        break;
                    case 6:
                        room1NCount = rst.getInt(2);
                        lblCountRoom1N.setText(String.valueOf(room1NCount));
                        break;
                    case 7:
                        room2NCount = rst.getInt(2);
                        lblCountRoom2N.setText(String.valueOf(room2NCount));
                        break;
                    case 8:
                        room3NCount = rst.getInt(2);
                        lblCountRoom3N.setText(String.valueOf(room3NCount));
                        break;
                    case 9:
                        room4NCount = rst.getInt(2);
                        lblCountRoom4N.setText(String.valueOf(room4NCount));
                        break;
                    case 10:
                        room5NCount = rst.getInt(2);
                        lblCountRoom5N.setText(String.valueOf(room5NCount));
                        break;
                    default:
                        break;
                }
            }

            if (room1Count > 0 || room1NCount > 0) {
                panelRoom1.setBackground(Color.BLUE);
            }
            if (room2Count > 0 || room2NCount > 0) {
                panelRoom2.setBackground(Color.BLUE);
            }
            if (room3Count > 0 || room3NCount > 0) {
                panelRoom3.setBackground(Color.BLUE);
            }
            if (room4Count > 0 || room4NCount > 0) {
                panelRoom4.setBackground(Color.BLUE);
            }
            if (room5Count > 0 || room5NCount > 0) {
                panelRoom5.setBackground(Color.BLUE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error!", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barRoom1;
    private javax.swing.JPanel barRoom2;
    private javax.swing.JPanel barRoom3;
    private javax.swing.JPanel barRoom4;
    private javax.swing.JPanel barRoom5;
    private javax.swing.JPanel barRoomN1;
    private javax.swing.JPanel barRoomN2;
    private javax.swing.JPanel barRoomN3;
    private javax.swing.JPanel barRoomN4;
    private javax.swing.JPanel barRoomN5;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblCountRoom1;
    private javax.swing.JLabel lblCountRoom1N;
    private javax.swing.JLabel lblCountRoom2;
    private javax.swing.JLabel lblCountRoom2N;
    private javax.swing.JLabel lblCountRoom3;
    private javax.swing.JLabel lblCountRoom3N;
    private javax.swing.JLabel lblCountRoom4;
    private javax.swing.JLabel lblCountRoom4N;
    private javax.swing.JLabel lblCountRoom5;
    private javax.swing.JLabel lblCountRoom5N;
    private javax.swing.JLabel lblFrameHeading;
    private javax.swing.JLabel lblFrameHeading11;
    private javax.swing.JLabel lblFrameHeading13;
    private javax.swing.JLabel lblFrameHeading15;
    private javax.swing.JLabel lblFrameHeading17;
    private javax.swing.JLabel lblFrameHeading19;
    private javax.swing.JLabel lblFrameHeading2;
    private javax.swing.JLabel lblFrameHeading21;
    private javax.swing.JLabel lblFrameHeading22;
    private javax.swing.JLabel lblFrameHeading23;
    private javax.swing.JLabel lblFrameHeading24;
    private javax.swing.JLabel lblFrameHeading3;
    private javax.swing.JLabel lblFrameHeading30;
    private javax.swing.JLabel lblFrameHeading31;
    private javax.swing.JLabel lblFrameHeading5;
    private javax.swing.JLabel lblFrameHeading7;
    private javax.swing.JLabel lblFrameHeading9;
    private javax.swing.JLabel lblHome22;
    private javax.swing.JLabel lblHome25;
    private javax.swing.JLabel lblHome26;
    private javax.swing.JLabel lblHome27;
    private javax.swing.JLabel lblHome28;
    private javax.swing.JLabel lblHome29;
    private javax.swing.JLabel lblHome30;
    private javax.swing.JLabel lblHome31;
    private javax.swing.JLabel lblHome32;
    private javax.swing.JLabel lblHome33;
    private javax.swing.JLabel lblHomeIcon;
    private javax.swing.JLabel lblHomeIcon1;
    private javax.swing.JLabel lblProfilePng;
    private javax.swing.JLabel lblProfilePng1;
    private javax.swing.JLabel lblProfilePng10;
    private javax.swing.JLabel lblProfilePng11;
    private javax.swing.JLabel lblProfilePng12;
    private javax.swing.JLabel lblProfilePng13;
    private javax.swing.JLabel lblProfilePng14;
    private javax.swing.JLabel lblProfilePng3;
    private javax.swing.JLabel lblProfilePng6;
    private javax.swing.JLabel lblProfilePng7;
    private javax.swing.JLabel lblProfilePng8;
    private javax.swing.JLabel lblProfilePng9;
    private javax.swing.JLabel lblReportIcon;
    private javax.swing.JPanel panelBgLeftSide1;
    private javax.swing.JPanel panelBgMain;
    private javax.swing.JPanel panelRoom1;
    private javax.swing.JPanel panelRoom2;
    private javax.swing.JPanel panelRoom3;
    private javax.swing.JPanel panelRoom4;
    private javax.swing.JPanel panelRoom5;
    private javax.swing.JTable tlbAllPatients;
    // End of variables declaration//GEN-END:variables
}
