/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LoginController;
import javax.swing.JOptionPane;

/**
 *
 * @author sanug
 */
public class SchedulleCheckView extends javax.swing.JFrame {

    /**
     * Creates new form SchedulleCheck
     */
    public SchedulleCheckView() {
        initComponents();
        lblErrorSchedulle.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMainHeading1 = new javax.swing.JLabel();
        lblHome16 = new javax.swing.JLabel();
        cmbSchedulle = new javax.swing.JComboBox<>();
        lblErrorSchedulle = new javax.swing.JLabel();
        btnEnter = new javax.swing.JButton();
        lblClose2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblMainHeading1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblMainHeading1.setForeground(new java.awt.Color(11, 60, 77));
        lblMainHeading1.setText("Your Schedulle");

        lblHome16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHome16.setForeground(new java.awt.Color(11, 60, 77));
        lblHome16.setText("Schedulle");

        cmbSchedulle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Not Selected--", "07.30 am - 09.30 am (Room No - 1)", "07.30 am - 09.30 am (Room No - 2)", "07.30 am - 09.30 am (Room No - 3)", "07.30 am - 09.30 am (Room No - 4)", "07.30 am - 09.30 am (Room No - 5)", "06.30 pm - 09.30 pm (Room No - 1)", "06.30 pm - 09.30 pm (Room No - 2)", "06.30 pm - 09.30 pm (Room No - 3)", "06.30 pm - 09.30 pm (Room No - 4)", "06.30 pm - 09.30 pm (Room No - 5)" }));
        cmbSchedulle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbSchedulleMouseClicked(evt);
            }
        });

        lblErrorSchedulle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblErrorSchedulle.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorSchedulle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/error (1).png"))); // NOI18N
        lblErrorSchedulle.setText("Error!");

        btnEnter.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(11, 60, 77));
        btnEnter.setText("Enter");
        btnEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 60, 77)));
        btnEnter.setContentAreaFilled(false);
        btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        btnEnter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEnterKeyPressed(evt);
            }
        });

        lblClose2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/close.png"))); // NOI18N
        lblClose2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblHome16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblErrorSchedulle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbSchedulle, 0, 224, Short.MAX_VALUE)))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(lblMainHeading1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClose2)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMainHeading1)
                    .addComponent(lblClose2))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSchedulle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHome16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorSchedulle)
                .addGap(35, 35, 35)
                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSchedulleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbSchedulleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSchedulleMouseClicked

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        if (cmbSchedulle.getSelectedIndex() == 0) {
            lblErrorSchedulle.setText("Make a selection!");
            lblErrorSchedulle.setVisible(true);
        } else {
            new LoginController().setSchedulleId(cmbSchedulle.getSelectedIndex());
            new AddAppointmentView().setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnEnterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEnterKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnterKeyPressed

    private void lblClose2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose2MouseClicked
        // TODO add your handling code here:
        int c = JOptionPane.showConfirmDialog(null, "Do you want to Logout From the System?", "Confirmation", JOptionPane.YES_NO_CANCEL_OPTION);

        if (c == 0) {

            new LoginController().setLogin(0, "", "");
            new LoginView().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_lblClose2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedulleCheckView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedulleCheckView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedulleCheckView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedulleCheckView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedulleCheckView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnter;
    private javax.swing.JComboBox<String> cmbSchedulle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose2;
    private javax.swing.JLabel lblErrorSchedulle;
    private javax.swing.JLabel lblHome16;
    private javax.swing.JLabel lblMainHeading1;
    // End of variables declaration//GEN-END:variables
}
